<a href="https://colab.research.google.com/github/sayan0506/Deep-Neural-Network-with-Pytorch-/blob/main/Pytorch_for_Deep_Learning_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# we are creating a 0 dimensional tensor of type float32
# tensors are heart of Deep lEarning
# pytorch is a deep learning framework
t1 = torch.tensor(4.0, dtype = torch.float32)

In [3]:
# we can find details
# it is the datatype of the values stored in the tensor
t1.dtype

torch.float32

In [4]:
# type of tensor
t1.type

<function Tensor.type>

In [5]:
# creatinfg tensor from a list
t2 = torch.tensor([1,2,3])
print(t2)

tensor([1, 2, 3])


In [6]:
# creating tensor from matrix
t3 = torch.tensor([[1,2],[3,4],[5,6]], dtype = torch.float32)
print(t3)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [7]:
# checking the dimension of the tensor
# a tensor should have a regular no of shape, if we change length in the sequence of rows, then it will throw error, so should be uniform in shape
# like no of elements in each row will be the same
print('shape: ', t3.shape)
print(t3.ndimension())

shape:  torch.Size([3, 2])
2


# Tensor operation and gradient

In [8]:
# creating three tensors
x = torch.tensor(3, dtype = torch.float32)
# here we are passing the requires_grad = True, so as to ensure that, ptorch can calculate gradient of that 0 d tensor with the help of backward porpagation
w = torch.tensor(4, dtype = torch.float32, requires_grad=True)
b = torch.tensor(5, dtype = torch.float32, requires_grad=True)

In [9]:
# linear regression(univariant)
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [10]:
# compute derivatives
y.backward()

In [11]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad.data)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with Numpy

In [12]:
# we can easily convert pytorch to numpy or vice-versa
# torch to numpy
print(y.detach().numpy())

17.0


In [13]:
# numpy to torch
import numpy as np

print(torch.from_numpy(np.array([1,2,3])))

tensor([1, 2, 3])


y.backward() works for any complex function, which is differentiable

In [14]:
# create random weights and biases tensors
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad= True)

In [15]:
print(w)
print(b)

tensor([[ 0.7481, -1.7116, -0.1718],
        [-1.1395, -0.3362, -1.0678]], requires_grad=True)
tensor([-1.4717,  0.1001], requires_grad=True)


In [16]:
# creating the linear regression model
# as w is multiplies with transpose thus. w.t() is the transpose of w
# in pytorch @ represents the matrix multiplication for torch tensors
def model(x):
  return x @ w.t() + b


In [17]:
# create inputs and targets tensors for the model
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58]], dtype = np.float32)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133]], dtype = np.float32)

In [18]:
# converting to pytorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [19]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])


In [20]:
# our data consist of 3 datapoints, each with 2 input features

In [21]:
# for model training creating a w and b
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad= True)
print(w)
print(b)

tensor([[ 0.6106, -0.6944, -0.5947],
        [-0.3698,  1.4410,  0.0671]], requires_grad=True)
tensor([-0.7660,  0.1691], requires_grad=True)


In [22]:
preds = model(inputs)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])


In [23]:
# defining a function for mean squared error
def mse(t1, t2):
  return torch.mean((t1 - t2)**2)
print(mse(targets, preds))

tensor(10262.1992, grad_fn=<MeanBackward0>)


In [24]:
# so loss is too high, thus we need to tune the parameters to reduce the loss

In [25]:
loss = mse(targets, preds)
loss.backward()
print(w)
print(w.grad)

tensor([[ 0.6106, -0.6944, -0.5947],
        [-0.3698,  1.4410,  0.0671]], requires_grad=True)
tensor([[-11485.5000, -14233.8438,  -7637.0854],
        [   888.0894,   1387.2500,    583.3824]])


In [26]:
print(b.grad)

tensor([-134.6172,   10.3994])


In [27]:
# setting grads to zero

w.grad.zero_()
b.grad.zero_()
print(w.grad, b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([0., 0.])


In [28]:
# adjusting weights and biases with Gradient descent
# we can't subtract gradient from w, so we introduce learning rate, i.e we include fraction or rate of grads, and by which we can also say that
# VVIMP: using learning rate we can continue to maintain the variance of the w.grad as constant, i.e maintain the grads in a limit
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

# here we are using with torch.no_grad() which ensures pytorch that, it should not do any grad calculation while subtracting

In [29]:
# in python for instant help about a module 
?torch

In [30]:
# as inputs is a tensor, to find out the value stored in the tensor instead of 0 d tensor, we use tensor.item()
inputs[0][0].item() 

73.0

In [36]:
# to reduce the loss run several epochs
for i in range(10000):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-05
    b -= b.grad * 1e-05
    w.grad.zero_()
    b.grad.zero_()

In [37]:
print(mse(preds, targets))

tensor(1.7731, grad_fn=<MeanBackward0>)


# Using nn modules in pytorch

In [38]:
import torch.nn as nn 

In [40]:
# inputs
inputs = np.array([[73, 67, 43], [91,88,64],[87,134,58],[102,43,37],
                   [69, 96, 70], [87,134,58], [102,43,37],[91,88,64]])
# targets
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119],
                    [119, 133],[22,37],[81,101]])

In [43]:
# converting to pytorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


# Dataset and dataloader

In [44]:
# the dataset or Tensordataset helps to access the rows of pytorch tensor or the dataset in a more efficient way
from torch.utils.data import TensorDataset

In [45]:
# creating instance of the TensorDataset class
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73,  67,  43],
         [ 91,  88,  64],
         [ 87, 134,  58]]), tensor([[ 56,  70],
         [ 81, 101],
         [119, 133]]))

In [46]:
train_ds[0]

(tensor([73, 67, 43]), tensor([56, 70]))

In [47]:
# so with the help of TensorDataset the (input, target) pair is created
# we passed inputs(x), targets(y) in the constructor of the TensorDataset class

In [48]:
# we can print row numbers
train_ds.__getitem__([0,1])

(tensor([[73, 67, 43],
         [91, 88, 64]]), tensor([[ 56,  70],
         [ 81, 101]]))

In [51]:
# by default a python list is created with that name of the object whe,ever, the TensorDataset class is instantiated
# TensorDataset helped to create the datasets for training,
# wheras the Dataloader helps to access the datapoints from the dataset
# we can create batches of data and so on, even we can use transforms on the data

In [52]:
from torch.utils.data import DataLoader

In [53]:
# define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

In [57]:
# so what dataloader object does, it creates a batch of minibtch size = 5, and it shuffles the samples while loading the data
for i, (xb, yb) in enumerate(train_dl):
  print(xb)
  print(yb)
  print(i)
  break
  # so what we see is, dataloader creates list of 2 minibatches, where 1st minibatch consists of 5 samples

tensor([[ 91,  88,  64],
        [ 73,  67,  43],
        [102,  43,  37],
        [ 87, 134,  58],
        [ 87, 134,  58]])
tensor([[ 81, 101],
        [ 56,  70],
        [ 22,  37],
        [119, 133],
        [119, 133]])
0


#Defining Linear regression and Gradient descent using Pytorch default **nn** module

In [60]:
# define model
# nn.Linear helps to create a linear regression model having input_features = 3, and output = 2
# so weights and bias matetrices are made accordingly
 
model = nn.Linear(in_features = 3, out_features=2)

In [61]:
print(model.weight)

Parameter containing:
tensor([[-0.0094,  0.2576, -0.4302],
        [-0.1923, -0.2488, -0.1865]], requires_grad=True)


In [62]:
print(model.bias)

Parameter containing:
tensor([-0.4907, -0.1793], requires_grad=True)


In [63]:
# we can see that, linear regression creates a neural network gaving single layer, consisting two nodes or output nodes
# that is why shape of the weight matrix = (3,2)