<a href="https://colab.research.google.com/github/sayan0506/Deep-Neural-Network-with-Pytorch-/blob/main/Pytorch_practice_materials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
a = torch.tensor([1,2,3], dtype=torch.float32)

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
a[0].item()

1.0

In [ ]:
# let's implement the concept of partial derivative

In [ ]:
# converting the pytorch tensor to numpy array
a.numpy()

array([1., 2., 3.], dtype=float32)

In [ ]:
a.ndimension()

1

In [ ]:
b = a.view(-1,1)

In [ ]:
b.ndimension()

2

In [ ]:
b.numpy()

array([[1.],
       [2.],
       [3.]], dtype=float32)

In [ ]:
b*b

tensor([[1.],
        [4.],
        [9.]])

In [ ]:
torch.dot(a,a.T)

tensor(14.)

In [ ]:
ls = a.tolist()

In [ ]:
ls

[1.0, 2.0, 3.0]

In [ ]:
# using linspace in pytorch
c = torch.linspace(-2,2,steps = 5, dtype = torch.float32)

In [ ]:
c

tensor([-2., -1.,  0.,  1.,  2.])

In [ ]:
c.type()

'torch.FloatTensor'

In [ ]:
c = c.type(torch.IntTensor)

In [ ]:
c.type()

'torch.IntTensor'

In [ ]:
c

tensor([-2, -1,  0,  1,  2], dtype=torch.int32)

In [ ]:
x = torch.tensor(2, dtype=torch.float32, requires_grad=True)

In [ ]:
z = x*x + 2*x + 1

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(7.)

In [ ]:
z

tensor(4., grad_fn=<MulBackward0>)

In [ ]:
x.grad_fn

In [ ]:
x

tensor(2., requires_grad=True)

In [ ]:
print(x.grad_fn)

None


In [ ]:
x

tensor(2., requires_grad=True)

In [ ]:
mean = torch.mean(x)

In [ ]:
mean

tensor(2., grad_fn=<MeanBackward0>)

In [ ]:
torch.std(x)

tensor(nan, grad_fn=<StdBackward0>)

In [ ]:
torch.sin(x)

tensor(0.9093, grad_fn=<SinBackward>)

In [ ]:
n = torch.sin(x)

In [ ]:
# as we passed req_grad = True in case of x, so we can't 
n.detach().numpy()

array(0.9092974, dtype=float32)

In [ ]:
import torch
from torch.utils.data import Dataset

In [ ]:
# defining class for dataset

class toy_set(Dataset):
  def __init__(self, length = 100, transform = None):
    self.len = length
    # x is a torch tensor containing ones, where shape passed as tuple(length, 2)
    # y is also torch tensor shape (lenght, 1)
    self.x = 2 * torch.ones(length, 2)
    self.y = torch.ones(length, 1)
    self.transform = transform

  def __getitem__(self, index):
    sample = self.x[index], self.y[index]
    if self.transform:
      sample = self.transform(sample)
    return sample_data

  def __len__(self):
    return self.len

In [ ]:
our_dataset = toy_set()

In [ ]:
print(our_dataset)

In [ ]:
# as we are using double underscores in the preficx and postfix of the len method name, so when we call len(our_dataset) object
# len overwrites the __len__() function 
print(len(our_dataset))

100


An abstract class representing a Dataset.

All datasets that represent a map from keys to data samples should subclass it. All subclasses should overwrite __getitem__(), supporting fetching a data sample for a given key. Subclasses could also optionally overwrite __len__(), which is expected to return the size of the dataset by many Sampler implementations and the default options of DataLoader.

In [15]:
# creating a dataset class
from torch.utils.data import Dataset
# Dataset is the abstract class

# in the toy_set class we are inheriting the torch Dataset abstrct class so as to implement it's functionalities 
class toy_set(Dataset):
  def __init__(self, length = 100, transform = None):
    # we are passing tuples as shape(100 elements of size 2)
    self.x = 2 * torch.ones(length, 2)
    self.y = torch.ones(length,1)
    
    # lentgh is assigned to the global varibale self.len
    # self is the this operator which points the object of the class and helps to acces the methods and variables in the class scope
    self.len = length
    self.transform = None

  def __getitem__(self, index):
    sample = self.x[index], self.y[index]
    if self.transform:
      sample = self.transform(sample)
    return sample

  def __len__(self):
    return self.len

# note here __init__, __getitem__, __len__ are the functionalities of Dataset abstract class we implemented, if any of them is missing it would have thrown error

In [16]:
t = toy_set()
# t is the instance of the class

In [19]:
# as we are using __len__(), we are calling len(toy_set object), thus the functionality of __len__ will overwrite the method of global len()
# so, len(t) will return self.len i.e. using __len__ function
# it returns the number of samples in the dataset
len(t)

100

In [22]:
# Note here, the t i.e. the dataset object behaves like a tuple of two elements, which is (x, y), x and y are torch tensors of defined shapes 
t[0]

(tensor([2., 2.]), tensor([1.]))

In [23]:
for i in range(10):
  print(t[i])

(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))


# Transforms

Implementing transforms

In [32]:
# creating a transform to add and multiply a value
# note: we basically pass the object keyword, when we don't want to add 
class add_mult(object):
  def __init__(self, addx = 1, muly = 1):
    self.addx = addx
    self.muly = muly

  def __call__(self, sample):
    x = sample[0]
    y = sample[1]
    x = x+ self.addx
    y = y * self.muly
    sample = x,y
    return sample



In [33]:
# we can implement transform in two way
# 1st one manually

print(t[0])
a_m = add_mult()
print(a_m(t[0]))

(tensor([2., 2.]), tensor([1.]))
(tensor([3., 3.]), tensor([1.]))


Please go through the below document for better understanding to know why python object is callable

1. A python class is always callable
2. A python object is callabable, iff, we use __call__() method

To check whether anything is callable

print(callable(object_name)) if returns True, then the python object is callable

https://www.journaldev.com/22761/python-callable-__call__#:~:text=__call__()%20example-,Python%20callable%20and%20__call__(),is%20a%20shorthand%20for%20x.&text=Note%20that%20callable()%20function,the%20object%20is%20not%20callable.

In [34]:
print(callable(t))

False


In [36]:
# as add_mult class implements __call__ method, so a_m object becomes callable through that method, and we don't need to execute that method seperately, the object itself is callable with the functionality of __call__()
# __call__() class
print(callable(a_m))

True


In [40]:
# 2nd method is transforming through the object class

a_m = add_mult()
dataset = toy_set(transform=a_m)
print(dataset[0])
print(dataset.__getitem__(0))

(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))


The most important thing is:

This double underscore(at prefix and postfix of a keyword) keywords in python are some special keywords in python which serve special purposes, we can't make such words, like __getitem__ we can use in method name, but __getdata__ we can't use, as there is no uch keyword in python to serve any purpose, or if we do so, it will not 

In [ ]:
# when we want to add multiple transform we can use Transforms Compose